### ISSUE TITLE
mixpanel-browser dependency version update

### ISSUE THREAD

**Issue by Federico-Rossi-TalentHouse** [apancutt/react-mixpanel-browser#24]
In the last release of mixpanel-browser ([2.45.0](https://github.com/mixpanel/mixpanel-js/releases/tag/v2.45.0)) the bundle size has been reduced. Would it be possible to update the dependency?

Thanks!

**Comment by apancutt** [comment]
This package already [targets the latest v2](https://github.com/apancutt/react-mixpanel-browser/blob/95ef8ffb237b18b91f47749e2034d8c283cd2740/package.json#L23) release of `mixpanel-browser` so if you're not getting 2.45.0 installed then your lock file needs updating, or you have another dependency holding it back.

Try using `yarn why mixpanel-browser`

**Comment by Federico-Rossi-TalentHouse** [comment]
Yes, you're right. I had to update the lock file manually to get the latest version and it worked.

Thanks!
